name: build
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
          docker run -p 8000:80 -d --name httpbin kennethreitz/httpbin
          sleep 2
          curl -v http://localhost:8000

