name: build
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: apt-get install -y curl docker.io
      - run: docker run -p 8000:80 -d --name httpbin kennethreitz/httpbin
      - run: curl -v http://localhost:8000

