name: build
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: docker run
        run: docker run -p 8000:80 -d --name httpbin kennethreitz/httpbin
      - name: curl
        uses: enflo/curl-action@master
        with:
          curl: -v http://localhost:8000